#!/bin/bash

set -e

echo "Starting modulairy nodejs-git container"

cd /var/www

if [ ! -z "$GIT_REPOSITORY_URL" ]
then
        echo "git clone from $GIT_REPOSITORY_URL"
        rm -rf * && git clone $GIT_REPOSITORY_URL .
        if [ ! -z "$GIT_BRANCH" ]
        then
            echo "Checkout $GIT_BRANCH branch"
            git checkout $GIT_BRANCH
        fi
fi

if [ ! -z "$INIT_SCRIPT" ]
then
    cd /
    echo "#\!/bin/bash" > initialize.sh
    echo $INIT_SCRIPT >> initialize.sh 
    chmod +x /initialize.sh

    echo "running initialize script..."
    exec $INIT_SCRIPT
fi

echo installing...
npm install
echo Starting nodejs...
if [ ! -z "$START_SCRIPT" ]
then
    cd /var/www
    echo "#\!/bin/bash" > starts.sh
    echo $START_SCRIPT >> starts.sh 
    chmod +x ./starts.sh
    ./starts.sh
else
    node server.js
fi
echo Closing...

